title: PHOENIX
description: Phoenix Design Concept by PhoenixTales
author: PhoenixTales
include:
  - "_img"
theme: null

livereload: true # Rebuilds the site and reloads the page.

# By default the original markdown files will be included as static pages in the output. To remove them from the output, set the remove_originals key to true. https://github.com/benbalter/jekyll-optional-front-matter?tab=readme-ov-file#configuration
optional_front_matter:
  remove_originals: true